title: "Termeh Bashiri"
name: "Termeh Bashiri"
description: "PhD Candidate in Physical Chemistry at Caltech"
url: "https://termehbashiri.com"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name: "Termeh Bashiri"
  avatar: "/assets/images/profile.JPG"
  bio: "PhD Candidate in Physical Chemistry at Caltech"
  location: "Pasadena, California"
  email: "termehbashiri@gmail.com"

  links:
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=waOL2ssAAAAJ&hl=en"
    - label: "Researchgate"
      icont: "fas fa-brands fa-researchgate"
      url: 

minimal_mistakes_skin: "dirt"

markdown: kramdown
