title: "Termeh Bashiri"
description: "PhD Candidate in Physical Chemistry at Caltech"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name: "Termeh Bashiri"
  avatar: "/assets/images/profile.JPG"
  bio: "PhD Candidate in Physical Chemistry at Caltech"
  location: "Pasadena, California"
  email: "termehbashiri@gmail.com"

  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=waOL2ssAAAAJ&hl=en"

minimal_mistakes_skin: "dirt"

markdown: kramdown
