remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

title: "Termeh Bashiri"
name: "Termeh Bashiri"
description: "PhD Candidate in Physical Chemistry at Caltech"
url: "https://termehbashiri.com"

plugins:
  - jekyll-include-cache

author:
  name: "Termeh Bashiri"
  avatar: "/assets/images/profile.JPG"
  bio: "PhD Candidate in Physical Chemistry at Caltech"
  location: "Pasadena, California"
  email: "tbashiri@caltech.edu"

  links:
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0001-6579-0742"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=waOL2ssAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/termehbashiri/"



markdown: kramdown
